### ISSUE TITLE
[💡 FEATURE REQUEST]: Add local folder or repo support

### ISSUE THREAD

**Issue by BarnabyDT** [roadrunner-server/velox#27]
### I have an idea!

While developing plug-ins for RR, it would be useful to be able to support loading plugins via a local directory instead of having to push code to a remote repository. This would reduce the developer feedback loop.

**Comment by rustatian** [comment]
Hey @BarnabyDT 👋 You may use replace in the Velox configuration. 

'''yaml

[github.plugins]
    # ref -> master, commit or tag
    logger = { ref = "master", owner = "roadrunner-server", repository = "logger", replace = "path/to/local/repo" }
'''

**Comment by BarnabyDT** [comment]
Ah great, thanks. Would it still be useful to support folders instead of repositories? I can take a look at implementing this if useful.

**Comment by rustatian** [comment]
> Hey @rustatian While implementing this I'm thinking of refactoring some of this project into more of community accepted project layout. Do you mind if I do that? If not, would you like this as a separate issue / PR?

I'm not sure what is `community accepted project layout`. Do you mean GitHub templates?

**Comment by BarnabyDT** [comment]
Well, a couple of things I've noticed while going through this so far:
* You've used the special internal folder for a couple of your modules, but others are outside of this in a flat structure. Internal prevents other people importing those packages so you can make changes without breaking your external API. I'm guessing the other packages like github, builder, commands are not supposed to be exposed externally.
* There's a random package called shared, even though there are generic named packages in the std library, it's still not great practise to have them in your own projects, I was thinking of just renaming this modules and moving it to internal.
* vx is your main entrypoint, I propose we move this under cmd/vx so if we need to add tooling later we can just create it under the CMD folder.

I've not finished getting accustomed to the code yet, so there may be others. It's also completely valid to keep this half flat structure if you want as well.

**Comment by rustatian** [comment]
Thanks for your proposals 👍🏻 

> You've used the special internal folder for a couple of your modules, but others are outside of this in a flat structure. Internal prevents other people importing those packages so you can make changes without breaking your external API. I'm guessing the other packages like github, builder, commands are not supposed to be exposed externally.

Not exactly. Commands are internal, however, other packages can be imported by the users. It's actually not a good practice to put all code into the internal package. `github/gitlab/builder` packages would have an interface (velox is in beta at the moment) and can be imported by third-party packages. I'm not expecting, that someone will need that, but, let's see.

> There's a random package called shared, even though there are generic named packages in the std library, it's still not great practise to have them in your own projects, I was thinking of just renaming this modules and moving it to internal.

`shared` package contains structures for other packages to use. I have plans to refactor it a little before the release to get rid of the `shared`. That was used as the initial implementation.

> vx is your main entrypoint, I propose we move this under cmd/vx so if we need to add tooling later we can just create it under the CMD folder.

`vx` entrypoint used to have a user-friendly name for the `go install` command. I actually don't want to have smt like: `go install github.com/roadrunner-server/velox/**cmd**/vx` instead of `go install github.com/roadrunner-server/velox/vx`

**Comment by rustatian** [comment]
@BarnabyDT 

Please use the `replace` configuration key to use a local folder replace. Velox is still in `beta`, so more detailed docs will come later (we work hard on fixing that).

[github.plugins]
    # ref -> master, commit or tag
    logger = { ref = "master", owner = "roadrunner-server", repository = "logger", replace = "path/to/local/repo" }
